[build]
  command = "./build.sh"
  publish = "src"

[build.environment]
  GO_IMPORT_PATH = "github.com/varun-batta/room-assignment-backend"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200